name: Manual approval

permissions:
  contents: write

on:
  workflow_call:
    inputs:
      VERSION:
        required: true
        type: string

jobs:
  approval:
    runs-on: ubuntu-latest
    # run only if a new version is detected and it is not a major version
    if: ${{ inputs.VERSION != '' && inputs.VERSION != '0.0.0' && !endsWith(inputs.VERSION, '.0.0') }}
    steps:
      - name: Wait for manual approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: Moritz010902
          issue-title: "Manual Approval neccessary for deployment"
          issue-body: "Please make sure that this repository is compatible with all the other services before procceeding."
          exclude-workflow-initiator-as-approver: false