name: Detect next version

permissions:
  contents: write

on:
  workflow_call:
    outputs:
      VERSION:
        value: ${{ jobs.detect_version.outputs.VERSION}}
      RELEASE_NOTES:
        value: ${{ jobs.detect_version.outputs.RELEASE_NOTES }}

jobs:
  detect_version:
    runs-on: ubuntu-latest

    outputs:
      VERSION: ${{ steps.semver.outputs.new_release_version }}
      RELEASE_NOTES: ${{ steps.semver.outputs.new_release_notes }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect next version and generate release notes
        id: semver
        uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # - name: Create release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     tag_name: v${{ steps.semver.outputs.new_release_version }}
      #     name: v${{ steps.semver.outputs.new_release_version }}
      #     body: ${{ steps.semver.outputs.RELEASE_NOTES }}
      #     #draft: true
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}