name: Detect next version

permissions:
  contents: write

on:
  workflow_call:
  workflow_dispatch:

jobs:
  detect_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect next version and generate release notes
        id: semver
        uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: true
          working_directory: ./.github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Versionsnummer und Release-Notes in Variablen speichern
        run: |
          echo "VERSION=${{ steps.semver.outputs.new_release_version }}" >> $GITHUB_ENV
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "${{ steps.semver.outputs.new_release_notes }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      
      - name: Draft-Release erstellen
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          body: ${{ env.RELEASE_NOTES }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}