name: Continuous Deployment

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  semver:
    uses: Moritz010902/test_devops/.github/workflows/semver-and-release-notes.yaml@main
  gh_release:
    uses: Moritz010902/test_devops/.github/workflows/github-release.yaml@main
    needs: semver
    with:
      VERSION: ${{ needs.semver.outputs.VERSION }}
      RELEASE_NOTES: ${{ needs.semver.outputs.RELEASE_NOTES }}