name: Continuous Deployment

permissions:
  contents: write
  issues: write

on:
  # push:
  #   branches: [ main, master ] 
  workflow_dispatch:

jobs:
  semver:
    uses: Moritz010902/test_devops/.github/workflows/semver-and-release-notes.yaml@main
    
  approval:
    uses: Moritz010902/test_devops/.github/workflows/manual-approval.yaml@main
    needs: semver
    with:
      VERSION: ${{ needs.semver.outputs.VERSION }}

  gh_release:
    uses: Moritz010902/test_devops/.github/workflows/github-release.yaml@main
    needs: [ semver, approval ]
    with:
      VERSION: ${{ needs.semver.outputs.VERSION }}
      RELEASE_NOTES: ${{ needs.semver.outputs.RELEASE_NOTES }}

  docker_build_and_push:
    uses: Moritz010902/test_devops/.github/workflows/docker-build-and-push.yaml@main
    needs: [ semver, approval ]
    with:
      version: ${{ needs.semver.outputs.VERSION }}