name: Test Aufruf von Semantic Version

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  semver:
    uses: Moritz010902/test_devops/.github/workflows/semantic-version.yaml@main

  test_call_semantic_version:
    needs: semver
    runs-on: ubuntu-latest
    steps:
      - name: Check env variables
        run: |
          echo "VERSION: ${{ needs.semver.outputs.VERSION }}"
          echo "RELEASE_NOTES: ${{ needs.semver.outputs.RELEASE_NOTES }}"